### ISSUE TITLE
Can't type double quotes in any blank space in ST4

### ISSUE THREAD

**Issue by DeclanKehoe** [sublimelsp/LSP-json#161]
I am using the latest version of Sublime Text 4, LSP Server is up to date, as is this package. I'm on an Intel Mac running Venture 13.5.2. Hopefully I'm not missing something, and I don't believe this is intended behaviour.
I cannot type double quotes unless the cursor is next to a character that is already highlighted as an error for not having valid syntax, or if I highlight something to be surrounded in double quotes. Otherwise, pressing for double quotes does literally nothing.
I have narrowed down the issue to this package, as the behaviour does not happen when it is disabled.

**Comment by rchl** [comment]
Can you reproduce with just LSP and LSP-json installed, running in [safe mode](https://www.sublimetext.com/docs/safe_mode.html)?

What is logged in Sublime Text console after executing `sublime.log_commands(True)` in the input field and trying to type a quote?

**Comment by DeclanKehoe** [comment]
I can reproduce the issue, but it should probably be noted that I've been running into the issue [here](https://github.com/wbond/package_control/issues/1612) with package control so I had to install the beta version of 4.0 into the safe mode installed packaged folder. The behaviour was exactly the same however, and only happened when this package was installed.

For example I went into the user preferences as that's immediately recognised as a JSON file for me to type in. In that case the log reads only `command: lsp_json_auto_complete` with no obvious response from the editor whenever I tried to type double quotes when there is whitespace to the right of the cursor.

<sub>ps thank you for responding, and sorry for taking a while to follow up. </sub>

**Comment by rchl** [comment]
Can you post the output of `LSP: Troubleshoot server` on the preferences file where you are seeing the issue?

**Comment by DeclanKehoe** [comment]
I can reproduce it in safe mode, double quotes will not show up unless there is a non-punctuation character on either side of the cursor, or if there are characters  highlighted to be wrapped in the double quotes. Any other scenario leads to nothing happening.

Second issue, LSP-json doesn't show up in the list of servers after hitting enter on `LSP: Troubleshoot server` in the command palette (the only options are `erlang-ls`, `ocaml`, `polymer-ide`, `ruby`, and `sorbet`, none of which I've actually installed!) I've tried this in both safe mode and regular mode, and ensured that it and LSP are the only packages other than Package Control that are installed.

**Comment by rchl** [comment]
So it sounds like there is some problem with the LSP-json installation. Please share the output from the ST console after restarting ST.

**Comment by DeclanKehoe** [comment]
```
startup, version: 4152 osx x64 channel: stable
SAFE MODE - overriding packages, state and cache paths
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Packages
state path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 1.54553
OpenGL Context Information:
  GL API Version: 4.1 INTEL-20.6.4
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) UHD Graphics 630
startup time: 1.62406
first paint time: 1.74777
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading plugin Package Control.plugin
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
ignored packages updated to: ["LSP-json", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "lsp_utils" 2.2.1 for Python 3.3
Package Control: Installed library "sublime_lib" 1.5.2 for Python 3.3
Package Control: Installed LSP-json 1.13.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading python 3.3 plugin LSP-json.commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/commands.py", line 1, in <module>
ImportError: No module named 'LSP'
reloading python 3.3 plugin LSP-json.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/plugin.py", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/schema_store.py", line 2, in <module>
ImportError: No module named 'LSP'
reloading python 3.3 plugin LSP-json.schema_store
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/schema_store.py", line 2, in <module>
ImportError: No module named 'LSP'
reloading settings Packages/User/Preferences.sublime-settings
```

This is the output in safe mode. Do you need the non-safe mode version as well?

**Comment by rchl** [comment]
You need to install the LSP package for LSP-json or any other LSP package to work.

**Comment by DeclanKehoe** [comment]
I'm so sorry, I've done it so many times I missed the step when I tried to show you the output. The behaviour is exactly the same, here is the full log. Apologies!

```
startup, version: 4152 osx x64 channel: stable
SAFE MODE - overriding packages, state and cache paths
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Packages
state path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 1.64955
OpenGL Context Information:
  GL API Version: 4.1 INTEL-20.6.4
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) UHD Graphics 630
startup time: 1.79242
first paint time: 2.02714
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading plugin Package Control.plugin
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "backrefs" 1.10.0 for Python 3.3
Package Control: Installed library "bracex" 2.1.1 for Python 3.3
Package Control: Installed library "mdpopups" 4.2.2 for Python 3.3
Package Control: Installed library "pathlib" 1.0.1 for Python 3.3
Package Control: Installed library "pyyaml" 5.1.1 for Python 3.3
Package Control: Installed library "wcmatch" 1.2.1 for Python 3.3
Package Control: Installed LSP 1.25.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP.boot
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["LSP-json", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "lsp_utils" 2.2.1 for Python 3.3
Package Control: Installed library "sublime_lib" 1.5.2 for Python 3.3
Package Control: Installed LSP-json 1.13.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP-json.commands
reloading python 3.3 plugin LSP-json.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/plugin.py", line 5, in <module>
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Lib/python33/lsp_utils/__init__.py", line 6, in <module>
    from .generic_client_handler import GenericClientHandler
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Lib/python33/lsp_utils/generic_client_handler.py", line 9, in <module>
    from package_control import events  # type: ignore
ImportError: cannot import name events
reloading python 3.3 plugin LSP-json.schema_store
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Unable to open /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Packages/Default/Preferences.sublime-settings
```

**Comment by rchl** [comment]
```
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Lib/python33/lsp_utils/generic_client_handler.py", line 9, in <module>
    from package_control import events  # type: ignore
```

That error seems to be related to Package Control 4

I'm sure that @deathaxe knows why it happens.

**Comment by predragnikolic** [comment]
```
Package Control: Settings change detected, clearing cache
ignored packages updated to: ["LSP", "Vintage"]
```
It looks like LSP is being put to the ignored packages

Can you remove LSP from that ignored packages list in Preferences.sublime-setting?

**Comment by rchl** [comment]
@predragnikolic I think that's kind of expected when installing packages.

@DeclanKehoe I have not been able to reproduce this issue with PC4. I think you are maybe installing some older version of PC4.

Try:
1. start in safe mode
2. install package control
3. add `"install_prereleases": ["Package Control"]` in PC setting
4. upgrade Package Control
5. install LSP
6. install LSP-json

Should have a log like this:

```
startup, version: 4156 osx arm64 channel: dev
SAFE MODE - overriding packages, state and cache paths
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/rafal/Library/Application Support/Sublime Text (Safe Mode)/Packages
state path: /Users/rafal/Library/Application Support/Sublime Text (Safe Mode)/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/rafal/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 0.968446
OpenGL Context Information:
  GL API Version: 4.1 Metal - 83.1
  GLSL Version: 4.10
  Vendor: Apple
  Renderer: Apple M2 Pro
startup time: 1.01572
first paint time: 1.05226
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin 0_package_control_loader.00-package_control
Unable to open /Users/rafal/Library/Application Support/Sublime Text (Safe Mode)/Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
ignored packages updated to: ["Package Control", "Vintage"]
unloading python 3.3 plugin Package Control.1_reloader
unloading python 3.3 plugin Package Control.2_bootstrap
unloading python 3.3 plugin Package Control.Package Control
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin Package Control.plugin
ignored packages updated to: ["0_package_control_loader", "Vintage"]
unloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: pausing indexer
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "backrefs" 1.10.0 for Python 3.3
Package Control: Installed library "bracex" 2.1.1 for Python 3.3
Package Control: Installed library "mdpopups" 4.2.2 for Python 3.3
Package Control: Installed library "pathlib" 1.0.1 for Python 3.3
Package Control: Installed library "pyyaml" 5.1.1 for Python 3.3
Package Control: Installed library "wcmatch" 1.2.1 for Python 3.3
Package Control: Installed LSP 1.25.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP.boot
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["LSP-json", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "lsp_utils" 2.2.1 for Python 3.3
Package Control: Installed library "sublime_lib" 1.5.2 for Python 3.3
Package Control: Installed LSP-json 1.13.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP-json.commands
reloading python 3.3 plugin LSP-json.plugin
reloading python 3.3 plugin LSP-json.schema_store
reloading settings Packages/User/Preferences.sublime-settings
Package Control: resuming indexer
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by DeclanKehoe** [comment]
@rchl Thank you for the ideas but following those steps ends with the exact same thing happening. Line 74 is where the `Package Control: All packages up-to-date!` message happened after adding the setting to PC settings and doing the upgrade command in the command palette. After that, exactly the same errors in the log and behaviour in the editor. 

```
startup, version: 4152 osx x64 channel: stable
SAFE MODE - overriding packages, state and cache paths
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Packages
state path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 1.86935
OpenGL Context Information:
  GL API Version: 4.1 INTEL-20.6.4
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) UHD Graphics 630
startup time: 1.98472
first paint time: 2.1665
environment variables loaded using: /bin/zsh -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading plugin Package Control.plugin
reloading settings Packages/User/Package Control.sublime-settings
Unable to open /Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Packages/Package Control/Package Control.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Settings change detected, clearing cache
Package Control: All packages up-to-date!
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "backrefs" 1.10.0 for Python 3.3
Package Control: Installed library "bracex" 2.1.1 for Python 3.3
Package Control: Installed library "mdpopups" 4.2.2 for Python 3.3
Package Control: Installed library "pathlib" 1.0.1 for Python 3.3
Package Control: Installed library "pyyaml" 5.1.1 for Python 3.3
Package Control: Installed library "wcmatch" 1.2.1 for Python 3.3
Package Control: Installed LSP 1.25.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP.boot
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["LSP-json", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Installed library "lsp_utils" 2.2.1 for Python 3.3
Package Control: Installed library "sublime_lib" 1.5.2 for Python 3.3
Package Control: Installed LSP-json 1.13.0
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin LSP-json.commands
reloading python 3.3 plugin LSP-json.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Installed Packages/LSP-json.sublime-package/plugin.py", line 5, in <module>
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Lib/python33/lsp_utils/__init__.py", line 6, in <module>
    from .generic_client_handler import GenericClientHandler
  File "/Users/xxx/Library/Application Support/Sublime Text (Safe Mode)/Lib/python33/lsp_utils/generic_client_handler.py", line 9, in <module>
    from package_control import events  # type: ignore
ImportError: cannot import name events
reloading python 3.3 plugin LSP-json.schema_store
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by rchl** [comment]
Maybe there is an issue with upgrading Package Control in case the initial version doesn't work properly (you said you have issues with the non-pre-release one). You should probably report that in the Package Control repo.

**Comment by rchl** [comment]
Looks like the issue was with PC itself so closing.

PC4 was released today so you can try reinstalling it and checking if that helps.
